README.md: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 300/300 [00:00<00:00, 101kB/s]
train-00000-of-00001.parquet: 100%|███████████████████████████████████████████████████████████████████████████████| 333k/333k [00:00<00:00, 1.50MB/s]
Generating train split: 100%|████████████████████████████████████████████████████████████████████████| 5006/5006 [00:00<00:00, 1344993.01 examples/s]
Traceback (most recent call last):
  File "/home/rtx3090/minhaz/projects/bitfest/Challange 1/test.py", line 183, in <module>
    train_df, val_df = prepare_dataset(dataset)
  File "/home/rtx3090/minhaz/projects/bitfest/Challange 1/test.py", line 34, in prepare_dataset
    'banglish': train_data['banglish'],
  File "/home/rtx3090/minhaz/projects/bitfest/bitfest/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 2780, in __getitem__
    return self._getitem(key)
  File "/home/rtx3090/minhaz/projects/bitfest/bitfest/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 2764, in _getitem
    pa_subtable = query_table(self._data, key, indices=self._indices)
  File "/home/rtx3090/minhaz/projects/bitfest/bitfest/lib/python3.9/site-packages/datasets/formatting/formatting.py", line 590, in query_table
    _check_valid_column_key(key, table.column_names)
  File "/home/rtx3090/minhaz/projects/bitfest/bitfest/lib/python3.9/site-packages/datasets/formatting/formatting.py", line 527, in _check_valid_column_key
    raise KeyError(f"Column {key} not in the dataset. Current columns in the dataset: {columns}")
KeyError: "Column banglish not in the dataset. Current columns in the dataset: ['bn', 'rm']"
Traceback (most recent call last):
  File "/home/rtx3090/minhaz/projects/bitfest/Challange 1/test.py", line 183, in <module>
    train_df, val_df = prepare_dataset(dataset)
  File "/home/rtx3090/minhaz/projects/bitfest/Challange 1/test.py", line 34, in prepare_dataset
    'banglish': train_data['banglish'],
  File "/home/rtx3090/minhaz/projects/bitfest/bitfest/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 2780, in __getitem__
    return self._getitem(key)
  File "/home/rtx3090/minhaz/projects/bitfest/bitfest/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 2764, in _getitem
    pa_subtable = query_table(self._data, key, indices=self._indices)
  File "/home/rtx3090/minhaz/projects/bitfest/bitfest/lib/python3.9/site-packages/datasets/formatting/formatting.py", line 590, in query_table
    _check_valid_column_key(key, table.column_names)
  File "/home/rtx3090/minhaz/projects/bitfest/bitfest/lib/python3.9/site-packages/datasets/formatting/formatting.py", line 527, in _check_valid_column_key
    raise KeyError(f"Column {key} not in the dataset. Current columns in the dataset: {columns}")
KeyError: "Column banglish not in the dataset. Current columns in the dataset: ['bn', 'rm']"
